### ISSUE TITLE
Do you know about some open-source device to take samples of insulin manually (externally)?

### ISSUE THREAD

**Issue by mutalis** [HeySugar/hey-sugar-app#6]
Hello Jamie !

Do you know about some open-source device to take samples of insulin manually (externally)?
I'd like to send the sampled data to an endpoint.

I read your publication at:
https://dev.to/jamieendeavour/managing-diabetes-with-jamstack-the-idea-2gi3

Thanks in advance,
Rodolfo.

**Comment by jamie-endeavour** [comment]
Hi @mutalis thanks for reaching out. I'm afraid i'm not sure of such a device. What data will you be hoping to retrieve from the insulin you are sampling? I might be able to ask around for you.

Thanks

**Comment by mutalis** [comment]
Hello @jamie-endeavour 

I'm looking for a blood glucose meter that has an open-source specification in order to be able to read the data and send it to a non-proprietary external App. I'm not looking for a device to take samples of insulin, sorry by the confusion it may cause because of my previous post.

I found that Roche and Bayer have a proprietary app for some of their blood glucose meters.
For example:
https://www.accu-chek.com/sites/g/files/iut341/f/mysugr_remote_diabetes_management_0.pdf

Any ideas on this matter are useful.

Have a nice day,
Rodolfo.

**Comment by jamie-endeavour** [comment]
Hey @mutalis no worries I had a feeling you meant glucose meter originally but I just wanted to clarify! I'm afraid I wouldn't know where to look for these specifications. I've used mysugr in the past but I was just under the impression that they had agreed a contract with the likes of Accu-Check in order to acquire connection to their hardware, I'm not aware of an open source specification.

However, what you might be interested in is another project called Nightscout which is an open source application that you can integrate with a CGM (Continuous Glucose Monitor). Again, this isn't my area so I might be wrong but it would be worth taking a look and perhaps reaching out to someone from their community as they would more than likely have a better idea.

The link for Nightscout is http://www.nightscout.info/

I hope this helps. I'm going to close the issue now since this isn't really relative to the HeySugar project but by all means if you have any questions or want to discuss further then I'm always happy to chat over Twitter - https://twitter.com/jamiebradley234

Best of luck!
